services:
  data_engineer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/interview_code/
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    entrypoint: [ "tail", "-f", "/dev/null" ]

  postgres:
    image: "postgres:13"
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postrgresql/data/

volumes:
  postgres_data:
